In [2]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np_array = np.asarray(my_list)
print("Array: ", np_array)
print("Shape of array: ", np_array.shape)
print("Data type of array elements: ", np_array.dtype)

Array:  [1 2 3 4 5]
Shape of array:  (5,)
Data type of array elements:  int64


**Force into another data type**

In [3]:
second_list = [1.2, 3.4, 5.6, 3.6, 20.5]
second_array = np.asarray(second_list, dtype = np.int64)
print("Array: ", second_array)

Array:  [ 1  3  5  3 20]


**Built-in Functions**

In [4]:
zero_array = np.zeros((2,5), dtype = int)
one_array = np.ones((3,6), dtype = int)
arange_array = np.arange(start = 0, step = 2, stop = 10)
linspace_array = np.linspace(start = 0, stop = 6, num = 3, dtype = int)
random_array = np.random.random(5)

print("Zero Array: ", zero_array)
print("One Array: ", one_array)
print("Arange Array: ", arange_array)
print("Linspace Array: ", linspace_array)
print("Random Array: ", random_array)

Zero Array:  [[0 0 0 0 0]
 [0 0 0 0 0]]
One Array:  [[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
Arange Array:  [0 2 4 6 8]
Linspace Array:  [0 3 6]
Random Array:  [0.73049183 0.717018   0.68352863 0.31710094 0.47243546]


**reshape**

In [5]:
my_array = np.arange(10)
my_array = np.reshape(my_array, (2,5))
print(my_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [6]:
my_order = np.reshape(my_array, (5,2))
print(my_order)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
# reshape np_boom numpy array to be [3,4] and change element 6 with 20

np_boom = np.arange(2, 14)
np_reshaped = np.reshape(np_boom, (3,4))
print(np_reshaped)
print("--------------------")
np_reshaped[1,0] = 20
print(np_reshaped)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
--------------------
[[ 2  3  4  5]
 [20  7  8  9]
 [10 11 12 13]]


**Access and Modify array elements**

In [8]:
empty = [i for i in range(10)]
emp_array = np.array(empty)
print(emp_array)
print("---------------------------------")
emp_array[2] = 50
emp_array[5] = 100
emp_array[8] = 150
print(emp_array)

[0 1 2 3 4 5 6 7 8 9]
---------------------------------
[  0   1  50   3   4 100   6   7 150   9]


In [9]:
high_list = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]
high_array = np.array(high_list)
print(high_array)
print("-------------------------------------")
high_array[0,1] = 100
high_array[1, 2] = 200
high_array[2, -2] = 300
print(high_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
-------------------------------------
[[  1 100   3   4   5]
 [  6   7 200   9  10]
 [ 11  12  13 300  15]]


In [10]:
# access 10 and 11
np_aar = np.array([[1,2,3], [2,3,5], [10,11,12]])
print(np_aar[2, 0:2])

[10 11]


**Slicing and Copying**

In [11]:
chincho = [[1,2,3], [4,5,6], [7,8,9]]
chin = np.array(chincho)
print(chin)
print("-------------------------")
print(chin[1:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-------------------------
[[5 6]]


In [12]:
# Without Copy Function original array has changed:

me = np.array([[1,2,3], [4,5,6], [7,8,9]])
you = me[1:2, 0:]
you[0,1] = 10
print("Me: ", me)
print("You: ", you)

Me:  [[ 1  2  3]
 [ 4 10  6]
 [ 7  8  9]]
You:  [[ 4 10  6]]


In [13]:
# After seed() function random numbers will be the same
# Let's make a copy of array, Original array won't change

np.random.seed(0)
us = np.random.random((3,3))
we = np.copy(us)
print(we)
print("--------------------------")
we[0,0] = 100
we[1,0] = 200
we[2,0] = 300
print(we[0:3, 0])
print("--------------------------")
print(us)

[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
--------------------------
[100. 200. 300.]
--------------------------
[[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]


In [14]:
tommy = np.ones((7,6), dtype = int)
artour = np.zeros((2,2), dtype = int)
tommy_copy = np.copy(tommy)
tommy_copy[2:4, 3:5] = artour

print(tommy)
print("----------------------------")
print(artour)
print("----------------------------")
print(tommy_copy)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
----------------------------
[[0 0]
 [0 0]]
----------------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 0 0 1]
 [1 1 1 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


**Insert, Append and Delete**

In [15]:
john = np.array([[1,2], [3,4]])
added = [[10,11], [12,13]]
print(john)
poly = np.insert(john, 0, np.array(added), axis = 0 )
aida = np.insert(john, 0, np.array(added), axis = 1)
print("-------------------------")
print(poly)
print("-------------------------")
print(aida)

[[1 2]
 [3 4]]
-------------------------
[[10 11]
 [12 13]
 [ 1  2]
 [ 3  4]]
-------------------------
[[10 12  1  2]
 [11 13  3  4]]


In [16]:
michael = np.array([['a', 'b', 'c'], ['d', 'e', 'f']])
pluss = [['g', 'h', 'i'], ['j', 'k', 'l']]
usa = np.append(michael, pluss, axis = 1)
print(usa)

[['a' 'b' 'c' 'g' 'h' 'i']
 ['d' 'e' 'f' 'j' 'k' 'l']]


In [17]:
usa = np.delete(usa, [0,1,2,3,4,5])
print(usa)

['d' 'e' 'f' 'j' 'k' 'l']


In [18]:
lion = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(lion)
print("--------------------------------")
lion = np.delete(lion, [1,3], axis = 0)
print(lion)
print("--------------------------------")
lion = np.delete(lion, 0, axis = 1)
print(lion)
print("--------------------------------")
lion = np.delete(lion, 0, axis = 0)
print(lion)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
--------------------------------
[[1 2 3]
 [7 8 9]]
--------------------------------
[[2 3]
 [8 9]]
--------------------------------
[[8 9]]


In [19]:
tiger = np.array([[20,14], [31, 41], [941, 678], [1468, 121]])
tiger_1 = np.copy(tiger)
tiger_2 = np.copy(tiger)
tiger_3 = np.copy(tiger)

tiger_1 = np.append(tiger_1, [3,4,5])
print(tiger_1)
print("------------------------------------------")
tiger_2 = np.insert(tiger_2, 1, [[15, 21], [41, 93]], axis = 0)
print(tiger_2)
print("------------------------------------------")
tiger_3 = np.delete(tiger_3, 0, axis = 0)
print(tiger_3)

[  20   14   31   41  941  678 1468  121    3    4    5]
------------------------------------------
[[  20   14]
 [  15   21]
 [  41   93]
 [  31   41]
 [ 941  678]
 [1468  121]]
------------------------------------------
[[  31   41]
 [ 941  678]
 [1468  121]]


**Index based on a condition**

In [23]:
# print elements bigger than 5

dog = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(dog[dog > 5])
print(dog > 5)

[6 7 8 9]
[[False False False]
 [False False  True]
 [ True  True  True]]


In [27]:
cat = np.array([[50,221,12], [21,30,541], [12,31,45]])
np_cat = cat[cat>=30]
print(np_cat)

[ 50 221  30 541  31  45]


**Broadcasting**

In [34]:
# multiplication of arrays

bear = np.array([[5, 10,15]])
monkey = np.array([[5, 2, 3]])
boom = bear * monkey
division = bear / monkey
lamp = bear * 10
print("boom: ", boom)
print("division: ", division)
print("lamp: ", lamp)

boom:  [[25 20 45]]
division:  [[1. 5. 5.]]
lamp:  [[ 50 100 150]]
