In [1]:
import numpy as np

In [2]:
# build array with your average weight per week:

day_weight = 185 - np.arange(5*7)/5
print(day_weight)

[185.  184.8 184.6 184.4 184.2 184.  183.8 183.6 183.4 183.2 183.  182.8
 182.6 182.4 182.2 182.  181.8 181.6 181.4 181.2 181.  180.8 180.6 180.4
 180.2 180.  179.8 179.6 179.4 179.2 179.  178.8 178.6 178.4 178.2]


In [3]:
avg_array = np.array([])
num_array = np.array([])
avg_number = 0
for item in range(len(day_weight)):
    num_array = np.append(num_array, day_weight[item])
    if len(num_array) == 7:
        avg_number = np.average(num_array)
        avg_array = np.append(avg_array, avg_number)
        # refresh variables:
        num_array = np.array([])
        avg_number = 0

print(avg_array)    

[184.4 183.  181.6 180.2 178.8]


In [4]:
# build array with your average weight per weekend:
# first solution:
first = np.array([])
second = np.array([])
third = np.array([])
four = np.array([])
five = np.array([])
for item in range(len(day_weight)):
    if item <= 6:
        first = np.append(first, day_weight[item])
    elif item > 6 and item <= 13:
        second = np.append(second, day_weight[item])
    elif item > 13 and item <= 20:
        third = np.append(third, day_weight[item])
    elif item > 20 and item <= 27:
        four = np.append(four, day_weight[item])
    else:
        five = np.append(five, day_weight[item])

first = first[-2:]
second = second[-2:]
third = third[-2:]
four = four[-2:]
five = five[-2:]

answer_array = np.array([])
answer_array = np.append(answer_array, np.average(first))
answer_array = np.append(answer_array, np.average(second))
answer_array = np.append(answer_array, np.average(third))
answer_array = np.append(answer_array, np.average(four))
answer_array = np.append(answer_array, np.average(five))
print(answer_array)

[183.9 182.5 181.1 179.7 178.3]


In [5]:
# second solution:
saturday = day_weight[5::7]
sunday = day_weight[6::7]
answer_1 = (saturday + sunday) / 2
print(answer_1)

[183.9 182.5 181.1 179.7 178.3]


In [6]:
# find silver quantity found in each coordinate:
np.random.seed(5555)
silver = np.random.randint(0,10,size = (7,7))
print(silver)

[[2 3 0 5 2 0 3]
 [8 8 0 7 1 5 3]
 [0 1 6 2 1 4 5]
 [4 0 8 9 9 8 7]
 [4 2 7 0 7 2 1]
 [9 8 9 2 5 0 8]
 [1 9 8 2 6 4 3]]


In [7]:
locations = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])
print(locations)

[[0 4]
 [2 2]
 [2 3]
 [5 1]
 [6 3]]


In [8]:
# first solution:
quantity = 0
for i in locations:
    quantity += silver[i[0],i[-1]]
print("found silver: ", quantity)

found silver:  20


In [9]:
# second solution:
answer_2 = silver[[0,2,2,5,6], [4,2,3,1,3]]
print("found silver: ", np.sum(answer_2))

found silver:  20


In [10]:
# third solution:
print(locations[:,0], locations[:,1])
answer_3 = silver[locations[:,0], locations[:,1]]
print("found silver: ", np.sum(answer_3))

[0 2 2 5 6] [4 2 3 1 3]
found silver:  20


In [11]:
# find differrence between (first array's first element, second array's last element) and 30
# first solution:
arr_1 = np.array([17.0, 28.0])
arr_2 = np.array([32.0, 36.0])
arr_1 = np.insert(arr_1, 1, np.average(arr_1))
arr_2 = np.insert(arr_2, 1, np.average(arr_2))
arr_2 = np.flip(arr_2)
answer_4 = np.array([])
answer_4 = np.append(answer_4, 30 - arr_1[-1])
answer_4 = np.append(answer_4, arr_2[0] - 30)
print(answer_4)

[2. 6.]


In [12]:
# second solution:
one = np.linspace(17,28,3)
one = np.append(one, np.flip(np.linspace(32,36,3)))
print(np.abs(one[2:4] - 30))

[2. 6.]


In [13]:
answer_5 = np.linspace([17,32], [28,36], 3)
print(np.abs(answer_5[2,:]-30))

[2. 6.]


In [14]:
# create a matrix where gives the absolute difference of the love scores for person i and person j
generator = np.random.default_rng(1010)
love_scores = np.round(generator.uniform(0, 100, 10),2)
answer = np.copy(love_scores)
print(answer)

[ 9.5  53.58 91.77 98.15 84.88 74.61 40.94 56.49  8.39 64.69]


In [15]:
result = np.array([])

for i in range(5):
    result = np.append(result, answer.min())
    result = np.append(result, answer.max())
    index_1 = np.where(answer == answer.min())
    index_2 = np.where(answer == answer.max())
    answer = np.delete(answer, [index_1, index_2])
print(answer)
print(result)

[]
[ 8.39 98.15  9.5  91.77 40.94 84.88 53.58 74.61 56.49 64.69]


In [16]:
result = result.reshape(5,2)
print(result)

[[ 8.39 98.15]
 [ 9.5  91.77]
 [40.94 84.88]
 [53.58 74.61]
 [56.49 64.69]]


In [17]:
result[:,1] = np.flip(result[:,1])
print(result)

[[ 8.39 64.69]
 [ 9.5  74.61]
 [40.94 84.88]
 [53.58 91.77]
 [56.49 98.15]]


In [18]:
np.set_printoptions(linewidth = 999)
answer_6 = np.abs(love_scores[:, None] - love_scores[None, :])
print(answer_6)

[[ 0.   44.08 82.27 88.65 75.38 65.11 31.44 46.99  1.11 55.19]
 [44.08  0.   38.19 44.57 31.3  21.03 12.64  2.91 45.19 11.11]
 [82.27 38.19  0.    6.38  6.89 17.16 50.83 35.28 83.38 27.08]
 [88.65 44.57  6.38  0.   13.27 23.54 57.21 41.66 89.76 33.46]
 [75.38 31.3   6.89 13.27  0.   10.27 43.94 28.39 76.49 20.19]
 [65.11 21.03 17.16 23.54 10.27  0.   33.67 18.12 66.22  9.92]
 [31.44 12.64 50.83 57.21 43.94 33.67  0.   15.55 32.55 23.75]
 [46.99  2.91 35.28 41.66 28.39 18.12 15.55  0.   48.1   8.2 ]
 [ 1.11 45.19 83.38 89.76 76.49 66.22 32.55 48.1   0.   56.3 ]
 [55.19 11.11 27.08 33.46 20.19  9.92 23.75  8.2  56.3   0.  ]]


In [19]:
# given 1d array, identify the first three values less than sixty and replace them with zero
generator = np.random.default_rng(80085)
scores = np.round(generator.uniform(low=30, high=100, size=15))
print(scores)

[68. 36. 76. 57. 56. 54. 63. 64. 36. 88. 80. 82. 84. 76. 42.]


In [20]:
# one way:
a = scores[scores < 60][0:3]
print(a)

[36. 57. 56.]


In [21]:
b = np.array([])
for i in a:
    ind = np.where(scores == i)
    b = np.append(b, ind)
print(b)

[1. 8. 3. 4.]


In [22]:
for i in b[0:3]:
    scores[int(i)] = 0
print(scores)

[68.  0. 76.  0. 56. 54. 63. 64.  0. 88. 80. 82. 84. 76. 42.]


In [23]:
# another solution
scores[(scores < 60).nonzero()[0][:3]] = 0
print(scores)

[68.  0. 76.  0.  0. 54. 63. 64.  0. 88. 80. 82. 84. 76. 42.]


In [24]:
# define 20 random unique locations where gold will be hidden:
field = np.zeros(shape = (10,10))
print(field)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [25]:
map_1 = np.arange(100)
# define random places:
rand_numb = np.array([])
while len(rand_numb) < 20:
    chosen = np.random.choice(map_1)
    if chosen not in rand_numb:
        rand_numb = np.append(rand_numb, chosen)
# reshape field:
map_1 = map_1.reshape(10,10)
# define coordinates:
locations = np.array([])
for item in rand_numb:
    locations = np.append(locations, np.where(map_1 == item))
locations = locations.reshape(20,2).astype(int)
print(locations)

[[3 4]
 [8 0]
 [0 7]
 [6 4]
 [4 5]
 [6 3]
 [2 9]
 [5 2]
 [8 9]
 [9 3]
 [2 0]
 [1 9]
 [1 3]
 [6 8]
 [7 6]
 [2 6]
 [6 1]
 [6 2]
 [8 1]
 [8 8]]


In [26]:
for i in range(20):
    field[locations[i][0], locations[i][1]] = np.random.randint(11,51)
print(field)

[[ 0.  0.  0.  0.  0.  0.  0. 48.  0.  0.]
 [ 0.  0.  0. 34.  0.  0.  0.  0.  0. 29.]
 [27.  0.  0.  0.  0.  0. 47.  0.  0. 21.]
 [ 0.  0.  0.  0. 20.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. 49.  0.  0.  0.  0.]
 [ 0.  0. 26.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. 39. 26. 27. 26.  0.  0.  0. 36.  0.]
 [ 0.  0.  0.  0.  0.  0. 33.  0.  0.  0.]
 [20. 17.  0.  0.  0.  0.  0.  0. 12. 15.]
 [ 0.  0.  0. 34.  0.  0.  0.  0.  0.  0.]]


In [27]:
print(field.ravel()[field.ravel() > 0])
print(len(field.ravel()[field.ravel() > 0]))

[48. 34. 29. 27. 47. 21. 20. 49. 26. 39. 26. 27. 26. 36. 33. 20. 17. 12. 15. 34.]
20


In [70]:
generator = np.random.default_rng(123)
ratings = np.round(generator.uniform(low = 0, high = 10.0, size = (10,2)))
ratings[[1,2,7,9], [0,0,0,0]] = np.nan
print(ratings)

[[ 7.  1.]
 [nan  2.]
 [nan  8.]
 [ 9.  3.]
 [ 8.  9.]
 [ 5.  2.]
 [ 8.  2.]
 [nan  6.]
 [ 9.  2.]
 [nan  5.]]


In [59]:
# first solution:
third = np.array([])
for i in ratings:
    if i[0]>0:
        third = np.append(third, i[0])
    else:
        third = np.append(third, i[1])
third = third.reshape(10,1)
print(third)

[[7.]
 [2.]
 [8.]
 [9.]
 [8.]
 [5.]
 [8.]
 [6.]
 [9.]
 [5.]]


In [60]:
ratings = np.append(ratings, third, axis = 1)
print(ratings)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


In [64]:
# second solution:
var = np.where(np.isnan(ratings[:,0]), ratings[:,1], ratings[:,0])
print(var)

[7. 2. 8. 9. 8. 5. 8. 6. 9. 5.]


In [69]:
answer = np.insert(arr = ratings, values = var, axis = 1, obj = 2)
print(answer)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]


In [72]:
var = var.reshape(10,1)
print(var)

[[7.]
 [2.]
 [8.]
 [9.]
 [8.]
 [5.]
 [8.]
 [6.]
 [9.]
 [5.]]


In [73]:
result = np.hstack((ratings, var))
print(result)

[[ 7.  1.  7.]
 [nan  2.  2.]
 [nan  8.  8.]
 [ 9.  3.  9.]
 [ 8.  9.  8.]
 [ 5.  2.  5.]
 [ 8.  2.  8.]
 [nan  6.  6.]
 [ 9.  2.  9.]
 [nan  5.  5.]]
